# Generated by Django 4.1.3 on 2022-12-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billapp', '0002_estimatedbill'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinedBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bilNo', models.IntegerField()),
                ('customerName', models.CharField(max_length=20)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('mobileNo', models.IntegerField()),
                ('amountValue', models.FloatField()),
                ('estimatedValue', models.FloatField()),
            ],
        ),
    ]
